version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8084:8084
    depends_on:
      - mysqldb


  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: userdata
      MYSQL_USER: ankit
      MYSQL_PASSWORD: ankit
      MYSQL_ROOT_PASSWORD: ankit